/// Native code generation for AArch64 (ARM64) and ARM32 architectures.
///
/// Maps NIR instructions to AArch64/ARM32 assembly in GAS syntax.
/// Uses AAPCS64 calling convention for 64-bit; AAPCS for 32-bit.
use std::collections::HashMap;
use nova_nir::ir::{AddrExpr, BasicBlock, Function, Instruction, Module};
use nova_nir::types::Value;

use crate::target::TargetSpec;

/// AArch64 general-purpose registers (x0-x30, excluding xzr=31).
const GREGS: &[&str] = &[
    "x0",  "x1",  "x2",  "x3",  "x4",  "x5",  "x6",  "x7",
    "x8",  "x9",  "x10", "x11", "x12", "x13", "x14", "x15",
    "x16", "x17", "x18", "x19", "x20", "x21", "x22", "x23",
    "x24", "x25", "x26", "x27", "x28", /* x29=fp */ "x30",
];

/// AAPCS64 parameter registers.
const PARAM_REGS: &[&str] = &["x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7"];

/// ARM32 registers.
const ARM32_REGS: &[&str] = &[
    "r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7",
    "r8", "r9", "r10", "r11", "r12", "sp", "lr", "pc",
];

/// ARM32 parameter registers.
const ARM32_PARAM_REGS: &[&str] = &["r0", "r1", "r2", "r3"];

/// AArch64 / ARM32 native code generator.
pub struct Aarch64Generator {
    lines: Vec<String>,
    #[allow(dead_code)]
    label_counter: usize,
    reg_map: HashMap<String, String>,
    next_reg: usize,
    spec: TargetSpec,
    current_func: String,
    is_32bit: bool,
}

impl Aarch64Generator {
    pub fn new(spec: TargetSpec) -> Self {
        let is_32bit = spec.pointer_width == 32;
        Aarch64Generator {
            lines: Vec::new(),
            label_counter: 0,
            reg_map: HashMap::new(),
            next_reg: 0,
            spec,
            current_func: String::new(),
            is_32bit,
        }
    }

    pub fn generate(&mut self, module: &Module) -> String {
        self.lines.clear();
        self.reg_map.clear();
        self.next_reg = 0;

        self.emit(&format!("// Generated by Nova {} Code Generator",
            if self.is_32bit { "ARM32" } else { "AArch64" }));
        self.emit(&format!("// Module: {}", module.name));
        self.emit(&format!("// Target: {}", self.spec.name));
        if self.is_32bit {
            self.emit(".arm");
            self.emit(".syntax unified");
        }
        self.emit(".text");
        self.emit(".globl _start");
        self.emit("");

        // Entry point
        self.emit("_start:");
        let main_name = module.functions.iter()
            .find(|f| f.name == "main")
            .map(|f| f.name.clone())
            .unwrap_or_else(|| module.functions[0].name.clone());
        self.emit(&format!("    bl {}", main_name));
        if self.is_32bit {
            self.emit("    mov r7, #1");
            self.emit("    svc #0");
        } else {
            self.emit("    mov x8, #93");
            self.emit("    svc #0");
        }
        self.emit("");

        for func in &module.functions {
            self.gen_function(func);
        }

        if !module.globals.is_empty() {
            self.emit(".data");
            for gvar in &module.globals {
                if let Value::GlobalVar { ref name, .. } = gvar {
                    self.emit(&format!("{}:", name));
                    if self.is_32bit {
                        self.emit("    .word 0");
                    } else {
                        self.emit("    .quad 0");
                    }
                }
            }
        }

        self.lines.join("\n")
    }

    fn gen_function(&mut self, func: &Function) {
        self.reg_map.clear();
        self.next_reg = 0;
        self.current_func = func.name.clone();

        let param_regs: &[&str] = if self.is_32bit {
            ARM32_PARAM_REGS
        } else {
            PARAM_REGS
        };
        for (i, param) in func.parameters.iter().enumerate() {
            if i < param_regs.len() {
                let pname = match param {
                    Value::FuncParam { ref name, .. } => name.as_str(),
                    _ => continue,
                };
                let vname = format!("%{}", pname);
                self.reg_map.insert(vname, param_regs[i].to_string());
            }
        }

        self.emit(&format!("{}:", func.name));
        if self.is_32bit {
            self.emit("    push {fp, lr}");
            self.emit("    mov fp, sp");
        } else {
            self.emit("    stp x29, x30, [sp, #-16]!");
            self.emit("    mov x29, sp");
        }

        for bb in &func.basic_blocks {
            self.gen_bb(bb);
        }
        self.emit("");
    }

    fn gen_bb(&mut self, bb: &BasicBlock) {
        if !bb.is_entry {
            self.emit(&format!(".L{}_{}:", self.current_func, bb.name));
        }
        for inst in &bb.instructions {
            self.gen_inst(inst);
        }
    }

    fn gen_inst(&mut self, inst: &Instruction) {
        match inst {
            // ── Arithmetic (flag-producing) ──
            Instruction::Add { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    mov {}, {}", d, l)); }
                self.emit(&format!("    add {}, {}, {}", d, d, r));
            }
            Instruction::Sub { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    mov {}, {}", d, l)); }
                self.emit(&format!("    sub {}, {}, {}", d, d, r));
            }
            Instruction::Mul { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    mul {}, {}, {}", d, l, r));
            }
            Instruction::Div { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    sdiv {}, {}, {}", d, l, r));
            }
            Instruction::Rem { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                let tmp = self.scratch_reg();
                self.emit(&format!("    sdiv {}, {}, {}", tmp, l, r));
                self.emit(&format!("    msub {}, {}, {}, {}", d, tmp, r, l));
            }
            Instruction::Divu { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    udiv {}, {}, {}", d, l, r));
            }
            Instruction::Remu { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                let tmp = self.scratch_reg();
                self.emit(&format!("    udiv {}, {}, {}", tmp, l, r));
                self.emit(&format!("    msub {}, {}, {}, {}", d, tmp, r, l));
            }

            // ── Immediate arithmetic ──
            Instruction::Addi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if *imm == 0 {
                    if d != s { self.emit(&format!("    mov {}, {}", d, s)); }
                } else {
                    self.emit(&format!("    add {}, {}, #{}", d, s, imm));
                }
            }
            Instruction::Subi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                self.emit(&format!("    sub {}, {}, #{}", d, s, imm));
            }
            Instruction::Neg { result, operand, .. } => {
                let d = self.reg(result);
                let s = self.reg(operand);
                self.emit(&format!("    neg {}, {}", d, s));
            }
            Instruction::Not { result, operand, .. } => {
                let d = self.reg(result);
                let s = self.reg(operand);
                self.emit(&format!("    mvn {}, {}", d, s));
            }

            // ── Bitwise ──
            Instruction::And { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    and {}, {}, {}", d, l, r));
            }
            Instruction::Or { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    orr {}, {}, {}", d, l, r));
            }
            Instruction::Xor { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    eor {}, {}, {}", d, l, r));
            }
            Instruction::Shl { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    lsl {}, {}, {}", d, l, r));
            }
            Instruction::Shr { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    asr {}, {}, {}", d, l, r));
            }

            // ── Immediate bitwise ──
            Instruction::Andi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                self.emit(&format!("    and {}, {}, #{}", d, s, imm));
            }
            Instruction::Ori { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                self.emit(&format!("    orr {}, {}, #{}", d, s, imm));
            }
            Instruction::Shli { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                self.emit(&format!("    lsl {}, {}, #{}", d, s, imm));
            }
            Instruction::Shri { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                self.emit(&format!("    asr {}, {}, #{}", d, s, imm));
            }

            // ── Memory ──
            Instruction::Load { result, addr } => {
                let d = self.reg(result);
                let a = self.addr_str(addr);
                self.emit(&format!("    ldr {}, {}", d, a));
            }
            Instruction::Loadi { result, base, offset } => {
                let d = self.reg(result);
                let b = self.reg(base);
                self.emit(&format!("    ldr {}, [{}, #{}]", d, b, offset));
            }
            Instruction::Store { value, addr } => {
                let a = self.addr_str(addr);
                let s = self.reg(value);
                self.emit(&format!("    str {}, {}", s, a));
            }
            Instruction::Storei { value, base, offset } => {
                let b = self.reg(base);
                let s = self.reg(value);
                self.emit(&format!("    str {}, [{}, #{}]", s, b, offset));
            }
            Instruction::Lea { result, addr } => {
                let d = self.reg(result);
                let a = self.addr_str(addr);
                self.emit(&format!("    adr {}, {}", d, a));
            }

            // ── Control flow ──
            Instruction::Br { target_bb } => {
                self.emit(&format!("    b .L{}_{}", self.current_func, target_bb));
            }
            Instruction::BrCond { cond, true_bb, false_bb } => {
                let c = self.reg(cond);
                self.emit(&format!("    cmp {}, #1", c));
                self.emit(&format!("    b.eq .L{}_{}", self.current_func, true_bb));
                self.emit(&format!("    b .L{}_{}", self.current_func, false_bb));
            }
            Instruction::Call { result, callee_name, args } => {
                let param_regs: &[&str] = if self.is_32bit {
                    ARM32_PARAM_REGS
                } else {
                    PARAM_REGS
                };
                for (i, arg) in args.iter().enumerate().take(param_regs.len()) {
                    let a = self.reg_or_imm(arg);
                    if a != param_regs[i] {
                        self.emit(&format!("    mov {}, {}", param_regs[i], a));
                    }
                }
                self.emit(&format!("    bl {}", callee_name));
                if let Some(ref d) = result {
                    let dreg = self.reg(d);
                    let ret_reg = if self.is_32bit { "r0" } else { "x0" };
                    if dreg != ret_reg {
                        self.emit(&format!("    mov {}, {}", dreg, ret_reg));
                    }
                }
            }
            Instruction::Ret { value } => {
                if let Some(ref v) = value {
                    let r = self.reg_or_imm(v);
                    let ret_reg = if self.is_32bit { "r0" } else { "x0" };
                    if r != ret_reg { self.emit(&format!("    mov {}, {}", ret_reg, r)); }
                }
                if self.is_32bit {
                    self.emit("    pop {fp, lr}");
                } else {
                    self.emit("    ldp x29, x30, [sp], #16");
                }
                self.emit("    ret");
            }

            // ── Flag consumers ──
            Instruction::TestEq { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, eq", d)); }
            Instruction::TestNe { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, ne", d)); }
            Instruction::TestLt { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, lt", d)); }
            Instruction::TestLe { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, le", d)); }
            Instruction::TestLtu { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, lo", d)); }
            Instruction::TestLeu { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, ls", d)); }
            Instruction::TestGe { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, ge", d)); }
            Instruction::TestGt { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, gt", d)); }
            Instruction::TestGeu { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, hs", d)); }
            Instruction::TestGtu { result, flags: _ } => { let d = self.reg(result); self.emit(&format!("    cset {}, hi", d)); }
            Instruction::TestOf { result, .. } => { let d = self.reg(result); self.emit(&format!("    cset {}, vs", d)); }
            Instruction::TestCf { result, .. } => { let d = self.reg(result); self.emit(&format!("    cset {}, cs", d)); }
            Instruction::TestSf { result, .. } => { let d = self.reg(result); self.emit(&format!("    cset {}, mi", d)); }

            // ── Moves ──
            Instruction::Movi { result, imm } => {
                let d = self.reg(result);
                self.emit(&format!("    mov {}, #{}", d, imm));
            }
            Instruction::Mov { result, src } => {
                let d = self.reg(result);
                let s = self.reg_or_imm(src);
                if d != s {
                    self.emit(&format!("    mov {}, {}", d, s));
                }
            }

            // ── Select ──
            Instruction::Select { result, cond, true_val, false_val } => {
                let d = self.reg(result);
                let c = self.reg(cond);
                let t = self.reg_or_imm(true_val);
                let f = self.reg_or_imm(false_val);
                self.emit(&format!("    cmp {}, #1", c));
                self.emit(&format!("    csel {}, {}, {}, eq", d, t, f));
            }

            Instruction::Phi { .. } => {}
            Instruction::Nop => {}

            // ── Float ──
            Instruction::Fadd { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    fmov s0, {}", l));
                self.emit(&format!("    fadd s0, s0, {}", r));
                self.emit(&format!("    fmov {}, s0", d));
            }
            Instruction::Fsub { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    fmov s0, {}", l));
                self.emit(&format!("    fsub s0, s0, {}", r));
                self.emit(&format!("    fmov {}, s0", d));
            }
            Instruction::Fmul { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    fmov s0, {}", l));
                self.emit(&format!("    fmul s0, s0, {}", r));
                self.emit(&format!("    fmov {}, s0", d));
            }
            Instruction::Fdiv { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    fmov s0, {}", l));
                self.emit(&format!("    fdiv s0, s0, {}", r));
                self.emit(&format!("    fmov {}, s0", d));
            }

            // ── Conversion ──
            Instruction::Sext { result, value, .. } |
            Instruction::Zext { result, value, .. } |
            Instruction::Trunc { result, value, .. } => {
                let d = self.reg(result);
                let s = self.reg_or_imm(value);
                if d != s {
                    self.emit(&format!("    mov {}, {}", d, s));
                }
            }

            // ── System ──
            Instruction::Syscall => { self.emit("    svc #0"); }
            Instruction::Bkpt => {
                if self.is_32bit { self.emit("    bkpt #0"); }
                else { self.emit("    brk #0"); }
            }
            Instruction::Fence => { self.emit("    dmb sy"); }

            // ── Stack ──
            Instruction::Push { value } => {
                let r = self.reg(value);
                if self.is_32bit {
                    self.emit(&format!("    push {{{}}}", r));
                } else {
                    self.emit(&format!("    str {}, [sp, #-16]!", r));
                }
            }
            Instruction::Pop { result } => {
                let d = self.reg(result);
                if self.is_32bit {
                    self.emit(&format!("    pop {{{}}}", d));
                } else {
                    self.emit(&format!("    ldr {}, [sp], #16", d));
                }
            }

            _ => {
                self.emit(&format!("// unsupported NIR: {:?}", inst));
            }
        }
    }

    // ── Helpers ──

    fn reg(&mut self, val: &Value) -> String {
        match val {
            Value::VReg { ref name, .. } => {
                let key = format!("%{}", name);
                if let Some(r) = self.reg_map.get(&key) {
                    return r.clone();
                }
                let reg = if self.is_32bit {
                    ARM32_REGS[self.fresh_vreg()].to_string()
                } else {
                    GREGS[self.fresh_vreg()].to_string()
                };
                self.reg_map.insert(key, reg.clone());
                reg
            }
            Value::ConstInt { value, .. } => format!("#{}", value),
            Value::GlobalVar { ref name, .. } => format!("={}", name),
            Value::FuncParam { ref name, .. } => {
                let key = format!("%{}", name);
                self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
            }
            _ => self.default_reg(),
        }
    }

    fn reg_or_imm(&mut self, val: &Value) -> String {
        match val {
            Value::ConstInt { value, .. } => format!("#{}", value),
            _ => self.reg(val),
        }
    }

    fn addr_str(&self, addr: &AddrExpr) -> String {
        let base_str = match &addr.base {
            Value::VReg { ref name, .. } => {
                let key = format!("%{}", name);
                self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
            }
            Value::GlobalVar { ref name, .. } => format!("={}", name),
            _ => self.default_reg(),
        };

        if let Some(ref index) = addr.index {
            let idx_str = match index {
                Value::VReg { ref name, .. } => {
                    let key = format!("%{}", name);
                    self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
                }
                _ => self.default_reg(),
            };
            let shift = match addr.scale {
                1 => 0, 2 => 1, 4 => 2, _ => 3,
            };
            if addr.offset != 0 {
                format!("[{}, {}, lsl #{}], #{}", base_str, idx_str, shift, addr.offset)
            } else {
                format!("[{}, {}, lsl #{}]", base_str, idx_str, shift)
            }
        } else {
            if addr.offset != 0 {
                format!("[{}, #{}]", base_str, addr.offset)
            } else {
                format!("[{}]", base_str)
            }
        }
    }

    fn default_reg(&self) -> String {
        if self.is_32bit { "r0".to_string() } else { "x0".to_string() }
    }

    fn scratch_reg(&self) -> String {
        if self.is_32bit { "r12".to_string() } else { "x16".to_string() }
    }

    fn fresh_vreg(&mut self) -> usize {
        let r = self.next_reg;
        let max = if self.is_32bit { ARM32_REGS.len() - 2 } else { GREGS.len() };
        self.next_reg = (self.next_reg + 1) % max;
        r
    }

    fn emit(&mut self, s: &str) {
        self.lines.push(s.to_string());
    }
}