/// Native code generation for x86_64 (AMD64) and x86 (IA-32) architectures.
///
/// Maps NIR instructions to x86_64/x86 assembly in GAS/AT&T syntax.
/// Uses System V AMD64 ABI calling convention for 64-bit; cdecl for 32-bit.
use std::collections::HashMap;
use nova_nir::ir::{AddrExpr, BasicBlock, Function, Instruction, Module};
use nova_nir::types::Value;

use crate::target::TargetSpec;

/// x86_64 register names in 64-bit mode.
const REGS_64: &[&str] = &[
    "%rax", "%rbx", "%rcx", "%rdx", "%rsi", "%rdi", "%rbp",
    "%r8",  "%r9",  "%r10", "%r11", "%r12", "%r13", "%r14", "%r15",
];

/// x86 32-bit register names (8 registers).
const REGS_32_X86: &[&str] = &[
    "%eax", "%ebx", "%ecx", "%edx", "%esi", "%edi", "%ebp", "%esp",
];

/// Param registers for System V AMD64 ABI (64-bit).
const PARAM_REGS_64: &[&str] = &["%rdi", "%rsi", "%rdx", "%rcx", "%r8", "%r9"];

/// x86_64/x86 native code generator.
pub struct X86_64Generator {
    lines: Vec<String>,
    label_counter: usize,
    reg_map: HashMap<String, String>,
    next_reg: usize,
    spec: TargetSpec,
    current_func: String,
    is_32bit: bool,
}

impl X86_64Generator {
    pub fn new(spec: TargetSpec) -> Self {
        let is_32bit = spec.pointer_width == 32;
        X86_64Generator {
            lines: Vec::new(),
            label_counter: 0,
            reg_map: HashMap::new(),
            next_reg: 0,
            spec,
            current_func: String::new(),
            is_32bit,
        }
    }

    pub fn generate(&mut self, module: &Module) -> String {
        self.lines.clear();
        self.reg_map.clear();
        self.next_reg = 0;

        self.emit(&format!("# Generated by Nova x86{} Code Generator",
            if self.is_32bit { " (32-bit)" } else { "_64" }));
        self.emit(&format!("# Module: {}", module.name));
        self.emit(&format!("# Target: {}", self.spec.name));
        if self.is_32bit {
            self.emit(".code32");
        }
        self.emit(".section .text");
        self.emit(".globl _start");
        self.emit("");

        self.emit("_start:");
        let main_name = module.functions.iter()
            .find(|f| f.name == "main")
            .map(|f| f.name.clone())
            .unwrap_or_else(|| module.functions[0].name.clone());
        self.emit(&format!("    call {}", main_name));
        if self.is_32bit {
            self.emit("    movl %eax, %ebx");
            self.emit("    movl $1, %eax");
            self.emit("    int $0x80");
        } else {
            self.emit("    movq %rax, %rdi");
            self.emit("    movq $60, %rax");
            self.emit("    syscall");
        }
        self.emit("");

        for func in &module.functions {
            self.gen_function(func);
        }

        if !module.globals.is_empty() {
            self.emit(".section .data");
            for gvar in &module.globals {
                if let Value::GlobalVar { ref name, .. } = gvar {
                    self.emit(&format!("{}:", name));
                    if self.is_32bit {
                        self.emit("    .long 0");
                    } else {
                        self.emit("    .quad 0");
                    }
                }
            }
        }

        self.lines.join("\n")
    }

    fn gen_function(&mut self, func: &Function) {
        self.reg_map.clear();
        self.next_reg = 0;
        self.current_func = func.name.clone();

        for (i, param) in func.parameters.iter().enumerate() {
            if i < PARAM_REGS_64.len() {
                let vr = self.fresh_vreg();
                let pname = match param {
                    Value::FuncParam { ref name, .. } => name.as_str(),
                    _ => continue,
                };
                let vname = format!("%{}", pname);
                let reg = if self.is_32bit {
                    REGS_32_X86[vr % REGS_32_X86.len()].to_string()
                } else {
                    REGS_64[vr].to_string()
                };
                self.reg_map.insert(vname, reg);
            }
        }

        self.emit(&format!("{}:", func.name));
        if self.is_32bit {
            self.emit("    pushl %ebp");
            self.emit("    movl %esp, %ebp");
        } else {
            self.emit("    pushq %rbp");
            self.emit("    movq %rsp, %rbp");
        }

        for bb in &func.basic_blocks {
            self.gen_bb(bb);
        }
        self.emit("");
    }

    fn gen_bb(&mut self, bb: &BasicBlock) {
        if !bb.is_entry {
            self.emit(&format!(".L{}_{}:", self.current_func, bb.name));
        }
        for inst in &bb.instructions {
            self.gen_inst(inst);
        }
    }

    fn gen_inst(&mut self, inst: &Instruction) {
        match inst {
            // ── Arithmetic (flag-producing) ──
            Instruction::Add { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, {}", self.addq(), r, d));
            }
            Instruction::Sub { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, {}", self.subq(), r, d));
            }
            Instruction::Mul { result, lhs, rhs, .. } => {
                let is32 = self.is_32bit;
                let d = self.reg(result);
                let rax_reg = if is32 { "%eax" } else { "%rax" };
                let movq = if is32 { "movl" } else { "movq" };
                let pushq = if is32 { "pushl" } else { "pushq" };
                let popq = if is32 { "popl" } else { "popq" };
                let imulq = if is32 { "imull" } else { "imulq" };
                if d != rax_reg {
                    self.emit(&format!("    {} {}", pushq, rax_reg));
                }
                let l = self.reg_or_imm(lhs);
                if l != rax_reg { self.emit(&format!("    {} {}, {}", movq, l, rax_reg)); }
                let r = self.reg(rhs);
                self.emit(&format!("    {} {}", imulq, r));
                if d != rax_reg {
                    self.emit(&format!("    {} {}, {}", movq, rax_reg, d));
                    self.emit(&format!("    {} {}", popq, rax_reg));
                }
            }
            Instruction::Div { result, lhs, rhs, .. } => {
                let is32 = self.is_32bit;
                let d = self.reg(result);
                let rax_reg = if is32 { "%eax" } else { "%rax" };
                let movq = if is32 { "movl" } else { "movq" };
                let pushq = if is32 { "pushl" } else { "pushq" };
                let popq = if is32 { "popl" } else { "popq" };
                let idivq = if is32 { "idivl" } else { "idivq" };
                let cqo = if is32 { "cltd" } else { "cqo" };
                self.emit(&format!("    {} %rdx", pushq));
                let l = self.reg_or_imm(lhs);
                if l != rax_reg { self.emit(&format!("    {} {}, {}", movq, l, rax_reg)); }
                self.emit(&format!("    {}", cqo));
                let r = self.reg(rhs);
                self.emit(&format!("    {} {}", idivq, r));
                if d != rax_reg { self.emit(&format!("    {} {}, {}", movq, rax_reg, d)); }
                self.emit(&format!("    {} %rdx", popq));
            }
            Instruction::Rem { result, lhs, rhs, .. } => {
                let is32 = self.is_32bit;
                let d = self.reg(result);
                let rax_reg = if is32 { "%eax" } else { "%rax" };
                let movq = if is32 { "movl" } else { "movq" };
                let pushq = if is32 { "pushl" } else { "pushq" };
                let popq = if is32 { "popl" } else { "popq" };
                let idivq = if is32 { "idivl" } else { "idivq" };
                let cqo = if is32 { "cltd" } else { "cqo" };
                let rdx = if is32 { "%edx" } else { "%rdx" };
                self.emit(&format!("    {} {}", pushq, rdx));
                let l = self.reg_or_imm(lhs);
                if l != rax_reg { self.emit(&format!("    {} {}, {}", movq, l, rax_reg)); }
                self.emit(&format!("    {}", cqo));
                let r = self.reg(rhs);
                self.emit(&format!("    {} {}", idivq, r));
                if d != rdx { self.emit(&format!("    {} {}, {}", movq, rdx, d)); }
                self.emit(&format!("    {} {}", popq, rdx));
            }
            Instruction::Divu { result, lhs, rhs, .. } => {
                let is32 = self.is_32bit;
                let d = self.reg(result);
                let rax_reg = if is32 { "%eax" } else { "%rax" };
                let movq = if is32 { "movl" } else { "movq" };
                let pushq = if is32 { "pushl" } else { "pushq" };
                let popq = if is32 { "popl" } else { "popq" };
                let divq = if is32 { "divl" } else { "divq" };
                let rdx = if is32 { "%edx" } else { "%rdx" };
                let xorq = if is32 { "xorl" } else { "xorq" };
                self.emit(&format!("    {} {}", pushq, rdx));
                let l = self.reg_or_imm(lhs);
                if l != rax_reg { self.emit(&format!("    {} {}, {}", movq, l, rax_reg)); }
                self.emit(&format!("    {} {}, {}", xorq, rdx, rdx));
                let r = self.reg(rhs);
                self.emit(&format!("    {} {}", divq, r));
                if d != rax_reg { self.emit(&format!("    {} {}, {}", movq, rax_reg, d)); }
                self.emit(&format!("    {} {}", popq, rdx));
            }
            Instruction::Remu { result, lhs, rhs, .. } => {
                let is32 = self.is_32bit;
                let d = self.reg(result);
                let rax_reg = if is32 { "%eax" } else { "%rax" };
                let movq = if is32 { "movl" } else { "movq" };
                let pushq = if is32 { "pushl" } else { "pushq" };
                let popq = if is32 { "popl" } else { "popq" };
                let divq = if is32 { "divl" } else { "divq" };
                let rdx = if is32 { "%edx" } else { "%rdx" };
                let xorq = if is32 { "xorl" } else { "xorq" };
                self.emit(&format!("    {} {}", pushq, rdx));
                let l = self.reg_or_imm(lhs);
                if l != rax_reg { self.emit(&format!("    {} {}, {}", movq, l, rax_reg)); }
                self.emit(&format!("    {} {}, {}", xorq, rdx, rdx));
                let r = self.reg(rhs);
                self.emit(&format!("    {} {}", divq, r));
                if d != rdx { self.emit(&format!("    {} {}, {}", movq, rdx, d)); }
                self.emit(&format!("    {} {}", popq, rdx));
            }

            // ── Immediate arithmetic ──
            Instruction::Addi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if *imm == 0 {
                    if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                } else {
                    self.emit(&format!("    {} {}({}), {}", self.leaq(), imm, s, d));
                }
            }
            Instruction::Subi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.subq(), imm, d));
            }
            Instruction::Muli { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}, {}", self.imulq(), imm, d, d));
            }
            Instruction::Neg { result, operand, .. } => {
                let d = self.reg(result);
                let s = self.reg(operand);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} {}", self.negq(), d));
            }
            Instruction::Not { result, operand, .. } => {
                let d = self.reg(result);
                let s = self.reg(operand);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} {}", self.notq(), d));
            }

            // ── Bitwise ──
            Instruction::And { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, {}", self.andq(), r, d));
            }
            Instruction::Or { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, {}", self.orq(), r, d));
            }
            Instruction::Xor { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, {}", self.xorq(), r, d));
            }
            Instruction::Shl { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, %rcx", self.movq(), r));
                self.emit(&format!("    {} %cl, {}", self.shlq(), d));
            }
            Instruction::Shr { result, lhs, rhs, .. } => {
                let d = self.reg(result);
                let l = self.reg_or_imm(lhs);
                let r = self.reg(rhs);
                if d != l { self.emit(&format!("    {} {}, {}", self.movq(), l, d)); }
                self.emit(&format!("    {} {}, %rcx", self.movq(), r));
                self.emit(&format!("    {} %cl, {}", self.sarq(), d));
            }

            // ── Immediate bitwise ──
            Instruction::Andi { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.andq(), imm, d));
            }
            Instruction::Ori { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.orq(), imm, d));
            }
            Instruction::Xori { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.xorq(), imm, d));
            }
            Instruction::Shli { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.shlq(), imm, d));
            }
            Instruction::Shri { result, lhs, imm, .. } => {
                let d = self.reg(result);
                let s = self.reg(lhs);
                if d != s { self.emit(&format!("    {} {}, {}", self.movq(), s, d)); }
                self.emit(&format!("    {} ${}, {}", self.sarq(), imm, d));
            }

            // ── Memory ──
            Instruction::Load { result, addr } => {
                let d = self.reg(result);
                let a = self.addr_str(addr);
                self.emit(&format!("    {} {}, {}", self.movq(), a, d));
            }
            Instruction::Loadi { result, base, offset } => {
                let d = self.reg(result);
                let b = self.reg(base);
                self.emit(&format!("    {} {}({}), {}", self.movq(), offset, b, d));
            }
            Instruction::Store { value, addr } => {
                let a = self.addr_str(addr);
                let s = self.reg(value);
                self.emit(&format!("    {} {}, {}", self.movq(), s, a));
            }
            Instruction::Storei { value, base, offset } => {
                let b = self.reg(base);
                let s = self.reg(value);
                self.emit(&format!("    {} {}, {}({})", self.movq(), s, offset, b));
            }
            Instruction::Lea { result, addr } => {
                let d = self.reg(result);
                let a = self.addr_str(addr);
                self.emit(&format!("    {} {}, {}", self.leaq(), a, d));
            }

            // ── Control flow ──
            Instruction::Br { target_bb } => {
                self.emit(&format!("    jmp .L{}_{}", self.current_func, target_bb));
            }
            Instruction::BrCond { cond, true_bb, false_bb } => {
                let c = self.reg(cond);
                self.emit(&format!("    {} $1, {}", self.cmpq(), c));
                self.emit(&format!("    je .L{}_{}", self.current_func, true_bb));
                self.emit(&format!("    jmp .L{}_{}", self.current_func, false_bb));
            }
            Instruction::Call { result, callee_name, args } => {
                self.emit(&format!("    {} %rcx", self.pushq()));
                self.emit(&format!("    {} %r8", self.pushq()));
                self.emit(&format!("    {} %r9", self.pushq()));
                for (i, arg) in args.iter().enumerate().take(6) {
                    let a = self.reg_or_imm(arg);
                    if a != PARAM_REGS_64[i] {
                        self.emit(&format!("    {} {}, {}", self.movq(), a, PARAM_REGS_64[i]));
                    }
                }
                self.emit(&format!("    call {}", callee_name));
                if let Some(ref d) = result {
                    let dreg = self.reg(d);
                    let rax = self.rax();
                    if dreg != rax {
                        self.emit(&format!("    {} {}, {}", self.movq(), rax, dreg));
                    }
                }
                self.emit(&format!("    {} %r9", self.popq()));
                self.emit(&format!("    {} %r8", self.popq()));
                self.emit(&format!("    {} %rcx", self.popq()));
            }
            Instruction::Ret { value } => {
                if let Some(ref v) = value {
                    let r = self.reg_or_imm(v);
                    let rax = self.rax();
                    if r != rax { self.emit(&format!("    {} {}, {}", self.movq(), r, rax)); }
                }
                if self.is_32bit {
                    self.emit("    popl %ebp");
                } else {
                    self.emit("    popq %rbp");
                }
                self.emit("    ret");
            }

            // ── Flag consumers ──
            Instruction::TestEq { result, .. } => { let d = self.reg(result); self.emit(&format!("    sete %al\n    movzbq %al, {}", d)); }
            Instruction::TestNe { result, .. } => { let d = self.reg(result); self.emit(&format!("    setne %al\n    movzbq %al, {}", d)); }
            Instruction::TestLt { result, .. } => { let d = self.reg(result); self.emit(&format!("    setl %al\n    movzbq %al, {}", d)); }
            Instruction::TestLe { result, .. } => { let d = self.reg(result); self.emit(&format!("    setle %al\n    movzbq %al, {}", d)); }
            Instruction::TestLtu { result, .. } => { let d = self.reg(result); self.emit(&format!("    setb %al\n    movzbq %al, {}", d)); }
            Instruction::TestLeu { result, .. } => { let d = self.reg(result); self.emit(&format!("    setbe %al\n    movzbq %al, {}", d)); }
            Instruction::TestGe { result, .. } => { let d = self.reg(result); self.emit(&format!("    setge %al\n    movzbq %al, {}", d)); }
            Instruction::TestGt { result, .. } => { let d = self.reg(result); self.emit(&format!("    setg %al\n    movzbq %al, {}", d)); }
            Instruction::TestGeu { result, .. } => { let d = self.reg(result); self.emit(&format!("    setae %al\n    movzbq %al, {}", d)); }
            Instruction::TestGtu { result, .. } => { let d = self.reg(result); self.emit(&format!("    seta %al\n    movzbq %al, {}", d)); }
            Instruction::TestOf { result, .. } => { let d = self.reg(result); self.emit(&format!("    seto %al\n    movzbq %al, {}", d)); }
            Instruction::TestCf { result, .. } => { let d = self.reg(result); self.emit(&format!("    setc %al\n    movzbq %al, {}", d)); }
            Instruction::TestSf { result, .. } => { let d = self.reg(result); self.emit(&format!("    sets %al\n    movzbq %al, {}", d)); }

            // ── Moves ──
            Instruction::Movi { result, imm } => {
                let d = self.reg(result);
                self.emit(&format!("    {} ${}, {}", self.movq(), imm, d));
            }
            Instruction::Mov { result, src } => {
                let d = self.reg(result);
                let s = self.reg_or_imm(src);
                if d != s {
                    self.emit(&format!("    {} {}, {}", self.movq(), s, d));
                }
            }

            // ── Select ──
            Instruction::Select { result, cond, true_val, false_val } => {
                let d = self.reg(result);
                let c = self.reg(cond);
                let t = self.reg_or_imm(true_val);
                let f = self.reg_or_imm(false_val);
                if d != f { self.emit(&format!("    {} {}, {}", self.movq(), f, d)); }
                self.emit(&format!("    {} $1, {}", self.cmpq(), c));
                let skip = self.next_label();
                self.emit(&format!("    jne .L_select_skip_{}", skip));
                self.emit(&format!("    {} {}, {}", self.movq(), t, d));
                self.emit(&format!(".L_select_skip_{}:", skip));
            }

            Instruction::Phi { .. } => {}
            Instruction::Nop => {}

            // ── Float (SSE) ──
            Instruction::Fadd { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    movss {}, %xmm0", l));
                self.emit(&format!("    addss {}, %xmm0", r));
                self.emit(&format!("    movss %xmm0, {}", d));
            }
            Instruction::Fsub { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    movss {}, %xmm0", l));
                self.emit(&format!("    subss {}, %xmm0", r));
                self.emit(&format!("    movss %xmm0, {}", d));
            }
            Instruction::Fmul { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    movss {}, %xmm0", l));
                self.emit(&format!("    mulss {}, %xmm0", r));
                self.emit(&format!("    movss %xmm0, {}", d));
            }
            Instruction::Fdiv { result, lhs, rhs } => {
                let d = self.reg(result);
                let l = self.reg(lhs);
                let r = self.reg(rhs);
                self.emit(&format!("    movss {}, %xmm0", l));
                self.emit(&format!("    divss {}, %xmm0", r));
                self.emit(&format!("    movss %xmm0, {}", d));
            }

            // ── Conversion ──
            Instruction::Sext { result, value, .. } |
            Instruction::Zext { result, value, .. } |
            Instruction::Trunc { result, value, .. } => {
                let d = self.reg(result);
                let s = self.reg_or_imm(value);
                if d != s {
                    self.emit(&format!("    {} {}, {}", self.movq(), s, d));
                }
            }
            Instruction::Sitofp { result, value } => {
                let d = self.reg(result);
                let s = self.reg(value);
                self.emit(&format!("    cvtsi2ss {}, %xmm0", s));
                self.emit(&format!("    movss %xmm0, {}", d));
            }
            Instruction::Fptosi { result, value } => {
                let d = self.reg(result);
                let s = self.reg(value);
                self.emit(&format!("    movss {}, %xmm0", s));
                self.emit(&format!("    cvttss2si %xmm0, {}", d));
            }

            // ── System ──
            Instruction::Syscall => { self.emit("    syscall"); }
            Instruction::Bkpt => { self.emit("    int3"); }
            Instruction::Hlt => { self.emit("    hlt"); }
            Instruction::Fence => { self.emit("    mfence"); }

            // ── Stack ──
            Instruction::Push { value } => {
                let r = self.reg(value);
                self.emit(&format!("    {} {}", self.pushq(), r));
            }
            Instruction::Pop { result } => {
                let d = self.reg(result);
                self.emit(&format!("    {} {}", self.popq(), d));
            }

            _ => {
                self.emit(&format!("# unsupported NIR instruction: {:?}", inst));
            }
        }
    }

    // ── Helpers ──

    fn fresh_vreg(&mut self) -> usize {
        let r = self.next_reg;
        let max = if self.is_32bit { REGS_32_X86.len() } else { REGS_64.len() };
        self.next_reg = (self.next_reg + 1) % max;
        r
    }

    fn next_label(&mut self) -> usize {
        let n = self.label_counter;
        self.label_counter += 1;
        n
    }

    fn reg(&mut self, val: &Value) -> String {
        match val {
            Value::VReg { ref name, .. } => {
                let key = format!("%{}", name);
                if let Some(r) = self.reg_map.get(&key) {
                    return r.clone();
                }
                let reg = if self.is_32bit {
                    REGS_32_X86[self.fresh_vreg()].to_string()
                } else {
                    let r = self.fresh_vreg();
                    let r = if REGS_64[r] == "%rbp" || REGS_64[r] == "%rsp" {
                        (r + 1) % REGS_64.len()
                    } else {
                        r
                    };
                    REGS_64[r].to_string()
                };
                self.reg_map.insert(key, reg.clone());
                reg
            }
            Value::ConstInt { value, .. } => format!("${}", value),
            Value::GlobalVar { ref name, .. } => format!("{}(%rip)", name),
            Value::FuncParam { ref name, .. } => {
                let key = format!("%{}", name);
                self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
            }
            _ => self.default_reg(),
        }
    }

    fn reg_or_imm(&mut self, val: &Value) -> String {
        match val {
            Value::ConstInt { value, .. } => format!("${}", value),
            _ => self.reg(val),
        }
    }

    fn addr_str(&self, addr: &AddrExpr) -> String {
        let base_str = match &addr.base {
            Value::VReg { ref name, .. } => {
                let key = format!("%{}", name);
                self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
            }
            Value::GlobalVar { ref name, .. } => {
                if self.is_32bit {
                    name.clone()
                } else {
                    format!("{}(%rip)", name)
                }
            }
            _ => self.default_reg(),
        };

        if let Some(ref index) = addr.index {
            let idx_str = match index {
                Value::VReg { ref name, .. } => {
                    let key = format!("%{}", name);
                    self.reg_map.get(&key).cloned().unwrap_or_else(|| self.default_reg())
                }
                _ => self.default_reg(),
            };
            if addr.offset != 0 {
                format!("{}({}, {}, {})", addr.offset, base_str, idx_str, addr.scale)
            } else {
                format!("({}, {}, {})", base_str, idx_str, addr.scale)
            }
        } else {
            if addr.offset != 0 {
                format!("{}({})", addr.offset, base_str)
            } else {
                format!("({})", base_str)
            }
        }
    }

    fn default_reg(&self) -> String {
        if self.is_32bit { "%eax".to_string() } else { "%rax".to_string() }
    }

    // ── 32/64-bit helpers ──
    fn movq(&self) -> &str { if self.is_32bit { "movl" } else { "movq" } }
    fn addq(&self) -> &str { if self.is_32bit { "addl" } else { "addq" } }
    fn subq(&self) -> &str { if self.is_32bit { "subl" } else { "subq" } }
    fn imulq(&self) -> &str { if self.is_32bit { "imull" } else { "imulq" } }
    fn _idivq(&self) -> &str { if self.is_32bit { "idivl" } else { "idivq" } }
    fn _divq(&self) -> &str { if self.is_32bit { "divl" } else { "divq" } }
    fn andq(&self) -> &str { if self.is_32bit { "andl" } else { "andq" } }
    fn orq(&self) -> &str { if self.is_32bit { "orl" } else { "orq" } }
    fn xorq(&self) -> &str { if self.is_32bit { "xorl" } else { "xorq" } }
    fn shlq(&self) -> &str { if self.is_32bit { "shll" } else { "shlq" } }
    fn sarq(&self) -> &str { if self.is_32bit { "sarl" } else { "sarq" } }
    fn negq(&self) -> &str { if self.is_32bit { "negl" } else { "negq" } }
    fn notq(&self) -> &str { if self.is_32bit { "notl" } else { "notq" } }
    fn cmpq(&self) -> &str { if self.is_32bit { "cmpl" } else { "cmpq" } }
    fn leaq(&self) -> &str { if self.is_32bit { "leal" } else { "leaq" } }
    fn pushq(&self) -> &str { if self.is_32bit { "pushl" } else { "pushq" } }
    fn popq(&self) -> &str { if self.is_32bit { "popl" } else { "popq" } }
    fn rax(&self) -> &str { if self.is_32bit { "%eax" } else { "%rax" } }
    fn _cqo(&self) -> &str { if self.is_32bit { "cltd" } else { "cqo" } }

    fn emit(&mut self, s: &str) {
        self.lines.push(s.to_string());
    }
}