[package]
name = "nova-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nova-nir = { path = "../nova-nir" }
nova-frontend = { path = "../nova-frontend" }
nova-hir = { path = "../nova-hir" }
nova-mir = { path = "../nova-mir" }
nova-codegen = { path = "../nova-codegen" }
thiserror.workspace = true