/// Pure RISC code generator.
///
/// Converts NIR instructions to RISC-only MacroCore-X assembly.
/// Expands composite instructions, stack ops, and flag consumers
/// into sequences of R/I/L/B-type instructions.
use std::collections::HashMap;

use nova_nir::ir::{AddrExpr, BasicBlock, Function, Instruction, Module};
use nova_nir::types::{IrType, Value};

use crate::regalloc::RegisterAllocator;
use crate::regalloc;

/// RISC code generator.
pub struct RiscGenerator {
    /// Output assembly lines.
    asm_lines: Vec<String>,
    /// Label counter for generating unique labels.
    label_counter: usize,
    /// Register allocator.
    reg_allocator: RegisterAllocator,
    /// Flag-to-arithmetic mapping for test lowering.
    flags_to_arith: HashMap<String, (String, Value, Value)>,
    /// Phi elimination inserts: pred_bb -> list of "mov dest, src" lines.
    phi_inserts: HashMap<String, Vec<String>>,
    /// Loop-back phi inserts: target_bb -> list of "mov dest, src" lines.
    phi_loop_inserts: HashMap<String, Vec<String>>,
    /// Current block name (for loop-back phi emission).
    current_block_name: String,
    /// Current function name (for label generation).
    current_func_name: String,
    /// Instruction position counter.
    inst_position: usize,
}

impl RiscGenerator {
    pub fn new() -> Self {
        RiscGenerator {
            asm_lines: Vec::new(),
            label_counter: 0,
            reg_allocator: RegisterAllocator::new(),
            flags_to_arith: HashMap::new(),
            phi_inserts: HashMap::new(),
            phi_loop_inserts: HashMap::new(),
            current_block_name: String::new(),
            current_func_name: String::new(),
            inst_position: 0,
        }
    }

    /// Generate RISC assembly for the entire module.
    pub fn generate(&mut self, module: &Module) -> String {
        self.asm_lines.clear();
        self.asm_lines.push("; Generated by NIR RISC Code Generator".to_string());
        self.asm_lines.push(format!("; Module: {}", module.name));
        self.asm_lines.push(format!("; Target: {}", module.target_triple));
        self.asm_lines.push(String::new());

        // Generate _start entry point
        let entry_name = module.functions.iter()
            .find(|f| f.name == "main")
            .map(|f| f.name.as_str())
            .unwrap_or(&module.functions[0].name);
        self.asm_lines.push("; Entry point".to_string());
        self.asm_lines.push("_start:".to_string());
        self.asm_lines.push(format!("    call .L_{}", entry_name));
        self.asm_lines.push("    ecall 0".to_string());
        self.asm_lines.push("    nop".to_string());
        self.asm_lines.push(String::new());

        for func in &module.functions {
            self.generate_function(func);
        }

        // Emit global variables
        if !module.globals.is_empty() {
            self.asm_lines.push("; Global variables".to_string());
            for gvar in &module.globals {
                if let Value::GlobalVar { ref name, .. } = gvar {
                    self.asm_lines.push(format!("@{}:", name));
                    self.asm_lines.push("    .word 0".to_string());
                }
            }
            self.asm_lines.push(String::new());
        }

        self.asm_lines.join("\n")
    }

    /// Generate RISC assembly for a single function.
    fn generate_function(&mut self, func: &Function) {
        // Reset per-function state
        self.flags_to_arith.clear();
        self.phi_inserts.clear();
        self.phi_loop_inserts.clear();
        self.inst_position = 0;
        self.current_func_name = func.name.clone();

        // Collect flag info for test lowering
        self.collect_flag_info(func);

        // Allocate registers
        self.reg_allocator.allocate(func);

        // Eliminate phi nodes
        self.eliminate_phi_nodes(func);

        // Emit function prologue
        self.asm_lines.push(format!("; Function: @{}", func.name));
        self.asm_lines.push(format!(".L_{}:", func.name));

        // Frame: save r15 (FP) and r31 (RA) via temp register r14, 32 bytes total
        // r31 can only be accessed via mov (R-type/I-type 5-bit fields), not st (L-type 4-bit)
        self.asm_lines.push("    subi r2, r2, 32".to_string());
        self.asm_lines.push("    st r15, [r2 + 0]".to_string());
        self.asm_lines.push("    mov r14, r31".to_string());
        self.asm_lines.push("    st r14, [r2 + 8]".to_string());
        self.asm_lines.push("    add r15, r2, r0".to_string());

        for bb in &func.basic_blocks {
            self.emit_block(bb, func);
        }

        // Epilogue block
        self.asm_lines.push(format!(".L_exit_{}:", func.name));
        self.asm_lines.push("    add r2, r15, r0".to_string());
        self.asm_lines.push("    ld r14, [r2 + 8]".to_string());
        self.asm_lines.push("    mov r31, r14".to_string());
        self.asm_lines.push("    ld r15, [r2 + 0]".to_string());
        self.asm_lines.push("    addi r2, r2, 32".to_string());
        self.asm_lines.push("    ret".to_string());
        self.asm_lines.push(String::new());
    }

    /// Collect flag-to-arithmetic mappings for test lowering.
    fn collect_flag_info(&mut self, func: &Function) {
        for bb in &func.basic_blocks {
            for inst in &bb.instructions {
                match inst {
                    Instruction::Add { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Sub { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Mul { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Mulh { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Div { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Divu { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Rem { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Remu { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::And { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Or { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Xor { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Shl { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Shr { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Sar { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Rotl { ref flags_result, ref lhs, ref rhs, .. }
                    | Instruction::Rotr { ref flags_result, ref lhs, ref rhs, .. } => {
                        if let Value::VReg { ref name, .. } = flags_result {
                            self.flags_to_arith.insert(
                                name.clone(),
                                (inst.opcode().to_string(), lhs.clone(), rhs.clone()),
                            );
                        }
                    }
                    Instruction::Neg { ref flags_result, ref operand, .. }
                    | Instruction::Not { ref flags_result, ref operand, .. } => {
                        if let Value::VReg { ref name, .. } = flags_result {
                            self.flags_to_arith.insert(
                                name.clone(),
                                (
                                    inst.opcode().to_string(),
                                    operand.clone(),
                                    Value::ConstInt { value: 0, ty: IrType::I64 },
                                ),
                            );
                        }
                    }
                    Instruction::Addi { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Subi { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Muli { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Andi { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Ori { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Xori { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Shli { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Shri { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Sari { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Rotli { flags_result: Some(ref flags_result), ref lhs, imm, .. }
                    | Instruction::Rotri { flags_result: Some(ref flags_result), ref lhs, imm, .. } => {
                        if let Value::VReg { ref name, .. } = flags_result {
                            self.flags_to_arith.insert(
                                name.clone(),
                                (
                                    inst.opcode().to_string(),
                                    lhs.clone(),
                                    Value::ConstInt { value: *imm, ty: IrType::I64 },
                                ),
                            );
                        }
                    }
                    _ => {}
                }
            }
        }
    }

    /// Eliminate phi nodes by inserting mov instructions in predecessor blocks.
    fn eliminate_phi_nodes(&mut self, func: &Function) {
        self.phi_inserts.clear();
        self.phi_loop_inserts.clear();

        for bb in &func.basic_blocks {
            let phi_insts: Vec<&Instruction> = bb
                .instructions
                .iter()
                .filter(|inst| matches!(inst, Instruction::Phi { .. }))
                .collect();

            if phi_insts.is_empty() {
                continue;
            }

            for phi in &phi_insts {
                if let Instruction::Phi { ref result, ref incoming } = phi {
                    if let Value::VReg { name: ref result_name, .. } = result {
                        self.reg_allocator.ensure_allocated(result_name);
                        for (val, pred_name) in incoming {
                            let src_name = self.reg_allocator.get_reg_name(val);
                            if pred_name == &bb.name {
                                // Loop-back edge
                                self.phi_loop_inserts
                                    .entry(bb.name.clone())
                                    .or_default()
                                    .push(format!("mov {}, {}", result_name, src_name));
                            } else {
                                self.phi_inserts
                                    .entry(pred_name.clone())
                                    .or_default()
                                    .push(format!("mov {}, {}", result_name, src_name));
                            }
                        }
                    }
                }
            }
        }
    }

    /// Emit assembly for a single basic block.
    fn emit_block(&mut self, bb: &BasicBlock, func: &Function) {
        self.current_block_name = bb.name.clone();
        if !bb.is_entry {
            self.asm_lines.push(format!(".L_{}_{}:", func.name, bb.name));
        } else {
            self.asm_lines.push(format!(".L_{}:", bb.name));
        }

        // Separate non-terminator and terminator instructions
        let (non_terms, terms): (Vec<&Instruction>, Vec<&Instruction>) = bb
            .instructions
            .iter()
            .partition(|inst| !is_terminator(inst));

        for inst in &non_terms {
            if matches!(inst, Instruction::Phi { .. }) {
                continue; // Phi nodes already eliminated
            }
            self.emit_instruction(inst);
            self.inst_position += 1;
        }

        // Emit phi-inserted mov instructions at the end of the block
        if let Some(insert_lines) = self.phi_inserts.get(&bb.name) {
            for line in insert_lines {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 3 && parts[0] == "mov" {
                    let dest_name = parts[1].trim_end_matches(',');
                    let src_name = parts[2];
                    let r_dest = self.reg_allocator.ensure_allocated(dest_name);
                    let r_src = self.reg_allocator.ensure_allocated(src_name);
                    if r_dest != r_src {
                        self.asm_lines.push(format!("    mov {}, {}", r_dest, r_src));
                    }
                }
            }
        }

        // Emit terminators
        for inst in &terms {
            self.emit_instruction(inst);
            self.inst_position += 1;
        }
    }

    /// Dispatch a single instruction to the appropriate handler.
    fn emit_instruction(&mut self, inst: &Instruction) {
        match inst {
            // Stack ops (RISC expansion)
            Instruction::Push { value } => self.emit_push(value),
            Instruction::Pop { result } => self.emit_pop(result),
            Instruction::Enter { frame_size } => self.emit_enter(*frame_size),
            Instruction::Leave => self.emit_leave(),

            // Arithmetic (same as CISC)
            Instruction::Add { .. }
            | Instruction::Sub { .. }
            | Instruction::Mul { .. }
            | Instruction::Mulh { .. }
            | Instruction::Div { .. }
            | Instruction::Divu { .. }
            | Instruction::Rem { .. }
            | Instruction::Remu { .. }
            | Instruction::And { .. }
            | Instruction::Or { .. }
            | Instruction::Xor { .. }
            | Instruction::Shl { .. }
            | Instruction::Shr { .. }
            | Instruction::Sar { .. }
            | Instruction::Rotl { .. }
            | Instruction::Rotr { .. } => self.emit_arith(inst),
            Instruction::Neg { result, operand, .. } => self.emit_neg(result, operand),
            Instruction::Not { result, operand, .. } => self.emit_not(result, operand),

            // Immediate
            Instruction::Addi { .. }
            | Instruction::Subi { .. }
            | Instruction::Muli { .. }
            | Instruction::Andi { .. }
            | Instruction::Ori { .. }
            | Instruction::Xori { .. }
            | Instruction::Shli { .. }
            | Instruction::Shri { .. }
            | Instruction::Sari { .. }
            | Instruction::Rotli { .. }
            | Instruction::Rotri { .. } => self.emit_immediate(inst),
            Instruction::Movi { result, imm } => self.emit_movi(result, *imm),
            Instruction::Mov { result, src } => self.emit_mov(result, src),

            // Flag consumers (RISC: generate comparison instruction)
            Instruction::TestEq { .. }
            | Instruction::TestNe { .. }
            | Instruction::TestLt { .. }
            | Instruction::TestLe { .. }
            | Instruction::TestLtu { .. }
            | Instruction::TestLeu { .. }
            | Instruction::TestOf { .. }
            | Instruction::TestCf { .. }
            | Instruction::TestSf { .. }
            | Instruction::TestGe { .. }
            | Instruction::TestGt { .. }
            | Instruction::TestGeu { .. }
            | Instruction::TestGtu { .. } => self.emit_test(inst),

            // Memory
            Instruction::Load { result, addr } => self.emit_load(result, addr),
            Instruction::Loadi { result, base, offset } => self.emit_loadi(result, base, *offset),
            Instruction::LoadSext { result, addr, from_type } => self.emit_load_sext(result, addr, from_type),
            Instruction::LoadZext { result, addr, from_type } => self.emit_load_zext(result, addr, from_type),
            Instruction::Store { value, addr } => self.emit_store(value, addr),
            Instruction::Storei { value, base, offset } => self.emit_storei(value, base, *offset),
            Instruction::Lea { result, addr } => self.emit_lea(result, addr),

            // Composite memory (RISC expansion)
            Instruction::MemAdd { addr, value } => self.emit_risc_mem_alu("add", value, addr),
            Instruction::MemSub { addr, value } => self.emit_risc_mem_alu("sub", value, addr),
            Instruction::MemAnd { addr, value } => self.emit_risc_mem_alu("and", value, addr),
            Instruction::MemOr { addr, value } => self.emit_risc_mem_alu("or", value, addr),
            Instruction::MemXor { addr, value } => self.emit_risc_mem_alu("xor", value, addr),
            Instruction::MemXchg { result, addr, value } => self.emit_risc_mem_xchg(result, value, addr),

            // Atomic
            Instruction::AtomicMemAdd { addr, value } => self.emit_atomic_add(addr, value),
            Instruction::AtomicMemXchg { result, addr, value } => self.emit_atomic_xchg(result, addr, value),
            Instruction::AtomicCas { result, addr, expected, desired } => self.emit_atomic_cas(result, addr, expected, desired),

            // Control flow
            Instruction::Br { target_bb } => self.emit_br(target_bb),
            Instruction::BrCond { cond, true_bb, false_bb } => self.emit_br_cond(cond, true_bb, false_bb),
            Instruction::Switch { value, default_bb, cases } => self.emit_switch(value, default_bb, cases),
            Instruction::Call { result, callee_name, args } => self.emit_call(result, callee_name, args),
            Instruction::CallIndirect { result, fnptr, args } => self.emit_call_indirect(result, fnptr, args),
            Instruction::Ret { value } => self.emit_ret(value),
            Instruction::TailCall { callee_name, args } => self.emit_tail_call(callee_name, args),

            // Float
            Instruction::Fadd { .. }
            | Instruction::Fsub { .. }
            | Instruction::Fmul { .. }
            | Instruction::Fdiv { .. }
            | Instruction::Fmin { .. }
            | Instruction::Fmax { .. } => self.emit_float_binary(inst),
            Instruction::Fneg { .. }
            | Instruction::Fabs { .. }
            | Instruction::Fsqrt { .. } => self.emit_float_unary(inst),
            Instruction::Ffma { result, a, b, c } => self.emit_ffma(result, a, b, c),
            Instruction::FcmpEq { .. }
            | Instruction::FcmpNe { .. }
            | Instruction::FcmpLt { .. }
            | Instruction::FcmpLe { .. }
            | Instruction::FcmpGt { .. }
            | Instruction::FcmpGe { .. }
            | Instruction::FcmpOrd { .. }
            | Instruction::FcmpUno { .. } => self.emit_fcmp(inst),

            // Conversion
            Instruction::Sext { .. }
            | Instruction::Zext { .. }
            | Instruction::Trunc { .. }
            | Instruction::Sitofp { .. }
            | Instruction::Uitofp { .. }
            | Instruction::Fptosi { .. }
            | Instruction::Fptoui { .. }
            | Instruction::Fpext { .. }
            | Instruction::Fptrunc { .. }
            | Instruction::Bitcast { .. } => self.emit_conv(inst),

            // System
            Instruction::Syscall => self.asm_lines.push("    syscall 0".to_string()),
            Instruction::Int { vector } => self.asm_lines.push(format!("    int {}", vector)),
            Instruction::Fence => self.asm_lines.push("    fence".to_string()),
            Instruction::Bkpt => self.asm_lines.push("    bkpt 0".to_string()),
            Instruction::Hlt => self.asm_lines.push("    hlt".to_string()),
            Instruction::Cli => self.asm_lines.push("    cli".to_string()),
            Instruction::Sti => self.asm_lines.push("    sti".to_string()),
            Instruction::Cpuid { result } => {
                self.asm_lines.push("    cpuid".to_string());
                let r_dest = self.reg_allocator.get_reg_name(result);
                if r_dest != "r0" {
                    self.asm_lines.push(format!("    mov {}, r0", r_dest));
                }
            }

            // Auxiliary
            Instruction::Select { result, cond, true_val, false_val } => {
                self.emit_select(result, cond, true_val, false_val);
            }
            Instruction::Nop => self.asm_lines.push("    nop".to_string()),
            Instruction::Phi { .. } => {} // Already eliminated

            // Vector
            Instruction::Vadd { .. }
            | Instruction::Vsub { .. }
            | Instruction::Vmul { .. }
            | Instruction::Vdiv { .. } => self.emit_vector_binary(inst),
            _ => {
                self.asm_lines.push(format!("    ; unhandled: {}", inst.opcode()));
            }
        }
    }

    // =====================================================================
    //  Stack ops (RISC expansion)
    // =====================================================================

    fn emit_push(&mut self, value: &Value) {
        // push → subi sp, sp, 8; st value, [sp]
        let r_val = self.reg_allocator.get_reg_name(value);
        self.asm_lines.push(format!("    ; [RISC] push expanded"));
        self.asm_lines.push("    subi r2, r2, 8".to_string());
        self.asm_lines.push(format!("    st {}, [r2 + 0]", r_val));
    }

    fn emit_pop(&mut self, result: &Value) {
        // pop → ld result, [sp]; addi sp, sp, 8
        let r_dest = self.reg_allocator.get_reg_name(result);
        self.asm_lines.push(format!("    ; [RISC] pop expanded"));
        self.asm_lines.push(format!("    ld {}, [r2 + 0]", r_dest));
        self.asm_lines.push("    addi r2, r2, 8".to_string());
    }

    fn emit_enter(&mut self, frame_size: i64) {
        // enter N → subi sp, sp, N; st r15, [sp]; st r31, [sp+8]; add r15, sp, r0
        self.asm_lines.push(format!("    ; [RISC] enter expanded"));
        self.asm_lines.push(format!("    subi r2, r2, {}", frame_size));
        self.asm_lines.push("    st r15, [r2 + 0]".to_string());
        self.asm_lines.push("    st r31, [r2 + 8]".to_string());
        self.asm_lines.push("    add r15, r2, r0".to_string());
    }

    fn emit_leave(&mut self) {
        // leave → add r2, r15, r0; ld r31, [r2+8]; ld r15, [r2+0]; addi r2, r2, N
        self.asm_lines.push(format!("    ; [RISC] leave expanded"));
        self.asm_lines.push("    add r2, r15, r0".to_string());
        self.asm_lines.push("    ld r31, [r2 + 8]".to_string());
        self.asm_lines.push("    ld r15, [r2 + 0]".to_string());
        // Note: addi r2, r2, N is emitted by the caller based on frame_size
    }

    // =====================================================================
    //  Arithmetic
    // =====================================================================

    fn emit_arith(&mut self, inst: &Instruction) {
        let opcode = inst.opcode();
        let (result, lhs, rhs) = match inst {
            Instruction::Add { result, lhs, rhs, .. }
            | Instruction::Sub { result, lhs, rhs, .. }
            | Instruction::Mul { result, lhs, rhs, .. }
            | Instruction::Mulh { result, lhs, rhs, .. }
            | Instruction::Div { result, lhs, rhs, .. }
            | Instruction::Divu { result, lhs, rhs, .. }
            | Instruction::Rem { result, lhs, rhs, .. }
            | Instruction::Remu { result, lhs, rhs, .. }
            | Instruction::And { result, lhs, rhs, .. }
            | Instruction::Or { result, lhs, rhs, .. }
            | Instruction::Xor { result, lhs, rhs, .. }
            | Instruction::Shl { result, lhs, rhs, .. }
            | Instruction::Shr { result, lhs, rhs, .. }
            | Instruction::Sar { result, lhs, rhs, .. }
            | Instruction::Rotl { result, lhs, rhs, .. }
            | Instruction::Rotr { result, lhs, rhs, .. } => (result, lhs, rhs),
            _ => return,
        };

        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_lhs = self.reg_allocator.get_reg_name(lhs);
        let r_rhs = self.reg_allocator.get_reg_name(rhs);

        let asm_op = match opcode {
            "add" => "add", "sub" => "sub", "mul" => "mul", "mulh" => "mulh",
            "div" => "div", "divu" => "divu", "rem" => "rem", "remu" => "remu",
            "and" => "and", "or" => "or", "xor" => "xor",
            "shl" => "shl", "shr" => "shr", "sar" => "sar",
            "rotl" => "rol", "rotr" => "ror",
            _ => opcode,
        };

        if opcode == "mulh" {
            self.asm_lines.push(format!("    ; mulh pseudo: upper bits"));
            self.asm_lines.push(format!("    mulh {}, {}, {}", r_dest, r_lhs, r_rhs));
            return;
        }

        if opcode == "rem" {
            self.asm_lines.push(format!("    ; rem pseudo: {} = {} % {}", r_dest, r_lhs, r_rhs));
            let r_temp = self.get_temp_reg(&[r_dest.as_str(), r_lhs.as_str(), r_rhs.as_str()]);
            self.asm_lines.push(format!("    div {}, {}, {}", r_temp, r_lhs, r_rhs));
            self.asm_lines.push(format!("    mul {}, {}, {}", r_temp, r_temp, r_rhs));
            self.asm_lines.push(format!("    sub {}, {}, {}", r_dest, r_lhs, r_temp));
            return;
        }

        if opcode == "remu" {
            self.asm_lines.push(format!("    ; remu pseudo: {} = {} % {}", r_dest, r_lhs, r_rhs));
            let r_temp = self.get_temp_reg(&[r_dest.as_str(), r_lhs.as_str(), r_rhs.as_str()]);
            self.asm_lines.push(format!("    divu {}, {}, {}", r_temp, r_lhs, r_rhs));
            self.asm_lines.push(format!("    mul {}, {}, {}", r_temp, r_temp, r_rhs));
            self.asm_lines.push(format!("    sub {}, {}, {}", r_dest, r_lhs, r_temp));
            return;
        }

        self.asm_lines.push(format!("    {} {}, {}, {}", asm_op, r_dest, r_lhs, r_rhs));
    }

    fn emit_neg(&mut self, result: &Value, operand: &Value) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_src = self.reg_allocator.get_reg_name(operand);
        self.asm_lines.push(format!("    sub {}, r0, {}", r_dest, r_src));
    }

    fn emit_not(&mut self, result: &Value, operand: &Value) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_src = self.reg_allocator.get_reg_name(operand);
        self.asm_lines.push(format!("    xori {}, {}, -1", r_dest, r_src));
    }

    // =====================================================================
    //  Immediate
    // =====================================================================

    fn emit_immediate(&mut self, inst: &Instruction) {
        let (result, lhs, imm) = match inst {
            Instruction::Addi { result, lhs, imm, .. }
            | Instruction::Subi { result, lhs, imm, .. }
            | Instruction::Muli { result, lhs, imm, .. }
            | Instruction::Andi { result, lhs, imm, .. }
            | Instruction::Ori { result, lhs, imm, .. }
            | Instruction::Xori { result, lhs, imm, .. }
            | Instruction::Shli { result, lhs, imm, .. }
            | Instruction::Shri { result, lhs, imm, .. }
            | Instruction::Sari { result, lhs, imm, .. }
            | Instruction::Rotli { result, lhs, imm, .. }
            | Instruction::Rotri { result, lhs, imm, .. } => (result, lhs, imm),
            _ => return,
        };

        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_lhs = self.reg_allocator.get_reg_name(lhs);
        let asm_op = inst.opcode();
        self.asm_lines.push(format!("    {} {}, {}, {}", asm_op, r_dest, r_lhs, imm));
    }

    fn emit_movi(&mut self, result: &Value, imm: i64) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        if (-8192..=8191).contains(&imm) {
            self.asm_lines.push(format!("    mov {}, {}", r_dest, imm));
        } else {
            self.asm_lines.push(format!("    movi {}, {}", r_dest, imm));
        }
    }

    fn emit_mov(&mut self, result: &Value, src: &Value) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_src = self.reg_allocator.get_reg_name(src);
        if r_dest != r_src {
            self.asm_lines.push(format!("    mov {}, {}", r_dest, r_src));
        }
    }

    // =====================================================================
    //  Flag consumers (RISC: generate comparison)
    // =====================================================================

    fn emit_test(&mut self, inst: &Instruction) {
        let (flags, result) = match inst {
            Instruction::TestEq { flags, result, .. }
            | Instruction::TestNe { flags, result, .. }
            | Instruction::TestLt { flags, result, .. }
            | Instruction::TestLe { flags, result, .. }
            | Instruction::TestLtu { flags, result, .. }
            | Instruction::TestLeu { flags, result, .. }
            | Instruction::TestOf { flags, result, .. }
            | Instruction::TestCf { flags, result, .. }
            | Instruction::TestSf { flags, result, .. }
            | Instruction::TestGe { flags, result, .. }
            | Instruction::TestGt { flags, result, .. }
            | Instruction::TestGeu { flags, result, .. }
            | Instruction::TestGtu { flags, result, .. } => (flags, result),
            _ => return,
        };

        let opcode = inst.opcode();
        let r_result = self.reg_allocator.get_reg_name(result);

        if let Value::VReg { name: ref flags_name, .. } = flags {
            if let Some((_, ref lhs, ref rhs)) = self.flags_to_arith.get(flags_name).cloned() {
                let r_lhs = self.reg_allocator.get_reg_name(&lhs);
                let r_rhs = self.reg_allocator.get_reg_name(&rhs);

                // ISA only supports eq, lt, ltu as R-type comparison instructions.
                // Derive all other comparisons from these three.
                match opcode {
                    "test_eq" => {
                        self.asm_lines.push(format!("    ; [RISC] test_eq → eq"));
                        self.asm_lines.push(format!("    eq {}, {}, {}", r_result, r_lhs, r_rhs));
                    }
                    "test_ne" => {
                        // ne = !eq → eq + xori 1
                        self.asm_lines.push(format!("    ; [RISC] test_ne → eq + xori"));
                        self.asm_lines.push(format!("    eq {}, {}, {}", r_result, r_lhs, r_rhs));
                        self.asm_lines.push(format!("    xori {}, {}, 1", r_result, r_result));
                    }
                    "test_lt" => {
                        self.asm_lines.push(format!("    ; [RISC] test_lt → lt"));
                        self.asm_lines.push(format!("    lt {}, {}, {}", r_result, r_lhs, r_rhs));
                    }
                    "test_le" => {
                        // le = !(rhs < lhs) → lt temp, rhs, lhs + xori result, temp, 1
                        let r_temp = self.get_temp_reg(&[&r_result, &r_lhs, &r_rhs]);
                        self.asm_lines.push(format!("    ; [RISC] test_le → lt(swapped) + xori"));
                        self.asm_lines.push(format!("    lt {}, {}, {}", r_temp, r_rhs, r_lhs));
                        self.asm_lines.push(format!("    xori {}, {}, 1", r_result, r_temp));
                    }
                    "test_ltu" => {
                        self.asm_lines.push(format!("    ; [RISC] test_ltu → ltu"));
                        self.asm_lines.push(format!("    ltu {}, {}, {}", r_result, r_lhs, r_rhs));
                    }
                    "test_leu" => {
                        // leu = !(rhs < lhs) unsigned → ltu temp, rhs, lhs + xori
                        let r_temp = self.get_temp_reg(&[&r_result, &r_lhs, &r_rhs]);
                        self.asm_lines.push(format!("    ; [RISC] test_leu → ltu(swapped) + xori"));
                        self.asm_lines.push(format!("    ltu {}, {}, {}", r_temp, r_rhs, r_lhs));
                        self.asm_lines.push(format!("    xori {}, {}, 1", r_result, r_temp));
                    }
                    "test_ge" => {
                        // ge = !(lhs < rhs) → lt + xori
                        self.asm_lines.push(format!("    ; [RISC] test_ge → lt + xori"));
                        self.asm_lines.push(format!("    lt {}, {}, {}", r_result, r_lhs, r_rhs));
                        self.asm_lines.push(format!("    xori {}, {}, 1", r_result, r_result));
                    }
                    "test_gt" => {
                        // gt = rhs < lhs → lt with swapped operands
                        self.asm_lines.push(format!("    ; [RISC] test_gt → lt(swapped)"));
                        self.asm_lines.push(format!("    lt {}, {}, {}", r_result, r_rhs, r_lhs));
                    }
                    "test_geu" => {
                        // geu = !(lhs < rhs) unsigned → ltu + xori
                        self.asm_lines.push(format!("    ; [RISC] test_geu → ltu + xori"));
                        self.asm_lines.push(format!("    ltu {}, {}, {}", r_result, r_lhs, r_rhs));
                        self.asm_lines.push(format!("    xori {}, {}, 1", r_result, r_result));
                    }
                    "test_gtu" => {
                        // gtu = rhs < lhs unsigned → ltu with swapped operands
                        self.asm_lines.push(format!("    ; [RISC] test_gtu → ltu(swapped)"));
                        self.asm_lines.push(format!("    ltu {}, {}, {}", r_result, r_rhs, r_lhs));
                    }
                    _ => {
                        self.asm_lines.push(format!("    ; {} - no producer, fallback", opcode));
                    }
                }
                return;
            }
        }
        self.asm_lines.push(format!("    ; {} - no producer, fallback", opcode));
    }

    // =====================================================================
    //  Memory
    // =====================================================================

    fn emit_load(&mut self, result: &Value, addr: &AddrExpr) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        self.emit_mem_op("ld", &r_dest, addr, false, "");
    }

    fn emit_loadi(&mut self, result: &Value, base: &Value, offset: i64) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_base = self.resolve_addr_base_simple(base);
        if offset >= 0 {
            self.asm_lines.push(format!("    ld {}, [{} + {}]", r_dest, r_base, offset));
        } else {
            self.asm_lines.push(format!("    ld {}, [{} - {}]", r_dest, r_base, -offset));
        }
    }

    fn emit_load_sext(&mut self, result: &Value, addr: &AddrExpr, from_type: &IrType) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let sz = match from_type {
            IrType::I8 => "b",
            IrType::I16 => "h",
            IrType::I32 => "w",
            _ => "",
        };
        self.emit_mem_op("lds", &r_dest, addr, false, sz);
    }

    fn emit_load_zext(&mut self, result: &Value, addr: &AddrExpr, from_type: &IrType) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let sz = match from_type {
            IrType::I8 => "b",
            IrType::I16 => "h",
            IrType::I32 => "w",
            _ => "",
        };
        self.emit_mem_op("ldu", &r_dest, addr, false, sz);
    }

    fn emit_store(&mut self, value: &Value, addr: &AddrExpr) {
        let r_val = self.reg_allocator.get_reg_name(value);
        self.emit_mem_op("st", &r_val, addr, true, "");
    }

    fn emit_storei(&mut self, value: &Value, base: &Value, offset: i64) {
        let r_val = self.reg_allocator.get_reg_name(value);
        let r_base = self.resolve_addr_base_simple(base);
        if offset >= 0 {
            self.asm_lines.push(format!("    st {}, [{} + {}]", r_val, r_base, offset));
        } else {
            self.asm_lines.push(format!("    st {}, [{} - {}]", r_val, r_base, -offset));
        }
    }

    fn emit_lea(&mut self, result: &Value, addr: &AddrExpr) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_base = self.resolve_addr_base(addr);

        if let Some(ref index) = addr.index {
            let r_index = self.reg_allocator.get_reg_name(index);
            self.asm_lines.push(format!(
                "    lda {}, {}, {}, {}",
                r_dest, r_base, r_index, addr.scale
            ));
            if addr.offset != 0 {
                if addr.offset > 0 {
                    self.asm_lines.push(format!("    addi {}, {}, {}", r_dest, r_dest, addr.offset));
                } else {
                    self.asm_lines.push(format!("    subi {}, {}, {}", r_dest, r_dest, -addr.offset));
                }
            }
        } else {
            if addr.offset >= 0 {
                self.asm_lines.push(format!("    addi {}, {}, {}", r_dest, r_base, addr.offset));
            } else {
                self.asm_lines.push(format!("    subi {}, {}, {}", r_dest, r_base, -addr.offset));
            }
        }
    }

    // =====================================================================
    //  Composite memory (RISC expansion)
    // =====================================================================

    fn emit_risc_mem_alu(&mut self, mnemonic: &str, r_val: &Value, addr: &AddrExpr) {
        // ld r_temp, [addr]; alu r_temp, r_temp, r_val; st r_temp, [addr]
        let val_str = self.reg_allocator.get_reg_name(r_val);
        let r_temp = self.get_temp_reg(&[&val_str]);
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);

        if let Some(ref index) = addr.index {
            let r_index = self.reg_allocator.get_reg_name(index);
            self.asm_lines.push(format!(
                "    ldr {}, [{} + {}*{}{}]",
                r_temp, r_base, r_index, addr.scale, off_str
            ));
            self.asm_lines.push(format!("    {} {}, {}, {}", mnemonic, r_temp, r_temp, val_str));
            self.asm_lines.push(format!(
                "    str {}, [{} + {}*{}{}]",
                r_temp, r_base, r_index, addr.scale, off_str
            ));
        } else {
            self.asm_lines.push(format!("    ld {}, [{}{}]", r_temp, r_base, off_str));
            self.asm_lines.push(format!("    {} {}, {}, {}", mnemonic, r_temp, r_temp, val_str));
            self.asm_lines.push(format!("    st {}, [{}{}]", r_temp, r_base, off_str));
        }
    }

    fn emit_risc_mem_xchg(&mut self, result: &Value, value: &Value, addr: &AddrExpr) {
        let r_result = self.reg_allocator.get_reg_name(result);
        let r_val = self.reg_allocator.get_reg_name(value);
        let r_temp = self.get_temp_reg(&[&r_result, &r_val]);
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);

        if let Some(ref index) = addr.index {
            let r_index = self.reg_allocator.get_reg_name(index);
            self.asm_lines.push(format!(
                "    ldr {}, [{} + {}*{}{}]",
                r_temp, r_base, r_index, addr.scale, off_str
            ));
            self.asm_lines.push(format!(
                "    str {}, [{} + {}*{}{}]",
                r_val, r_base, r_index, addr.scale, off_str
            ));
        } else {
            self.asm_lines.push(format!("    ld {}, [{}{}]", r_temp, r_base, off_str));
            self.asm_lines.push(format!("    st {}, [{}{}]", r_val, r_base, off_str));
        }
        self.asm_lines.push(format!("    mov {}, {}", r_result, r_temp));
    }

    // =====================================================================
    //  Atomic
    // =====================================================================

    fn emit_atomic_add(&mut self, addr: &AddrExpr, value: &Value) {
        let r_val = self.reg_allocator.get_reg_name(value);
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);
        let r_old = self.get_temp_reg(&[&r_val, &r_base]);
        let r_new = self.get_temp_reg(&[&r_val, &r_base, &r_old]);

        let loop_label = self.new_label("atomic_add");
        self.asm_lines.push(format!(".L_{}:", loop_label));
        self.asm_lines.push(format!("    ld {}, [{}{}]", r_old, r_base, off_str));
        self.asm_lines.push(format!("    add {}, {}, {}", r_new, r_old, r_val));
        self.asm_lines.push(format!("    cmpxchg {}, {}, [{}{}]", r_old, r_new, r_base, off_str));
        self.asm_lines.push(format!("    bne {}, {}, .L_{}", r_old, r_old, loop_label));
    }

    fn emit_atomic_xchg(&mut self, result: &Value, addr: &AddrExpr, value: &Value) {
        let r_result = self.reg_allocator.get_reg_name(result);
        let r_val = self.reg_allocator.get_reg_name(value);
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);

        self.asm_lines.push(format!("    xchg {}, [{}{}]", r_val, r_base, off_str));
        if r_result != r_val {
            self.asm_lines.push(format!("    mov {}, {}", r_result, r_val));
        }
    }

    fn emit_atomic_cas(&mut self, result: &Value, addr: &AddrExpr, expected: &Value, desired: &Value) {
        let r_expected = self.reg_allocator.get_reg_name(expected);
        let r_desired = self.reg_allocator.get_reg_name(desired);
        let r_result = self.reg_allocator.get_reg_name(result);
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);

        let r_temp = self.get_temp_reg(&[&r_expected, &r_desired, &r_result, &r_base]);
        self.asm_lines.push(format!("    mov {}, {}", r_temp, r_expected));
        self.asm_lines.push(format!("    cmpxchg {}, {}, [{}{}]", r_temp, r_desired, r_base, off_str));
        if r_result != r_temp {
            self.asm_lines.push(format!("    mov {}, {}", r_result, r_temp));
        }
    }

    // =====================================================================
    //  Control flow
    // =====================================================================

    fn emit_br(&mut self, target_bb: &str) {
        self.asm_lines.push(format!("    j .L_{}_{}", self.current_func_name, target_bb));
    }

    fn emit_br_cond(&mut self, cond: &Value, true_bb: &str, false_bb: &str) {
        let r_cond = self.reg_allocator.get_reg_name(cond);
        let true_label = format!(".L_{}_{}", self.current_func_name, true_bb);
        let false_label = format!(".L_{}_{}", self.current_func_name, false_bb);

        self.asm_lines.push(format!("    beq {}, r0, {}", r_cond, false_label));

        // Emit loop-back phi moves
        self.emit_loop_phi_moves();

        self.asm_lines.push(format!("    j {}", true_label));
    }

    fn emit_switch(&mut self, value: &Value, default_bb: &str, cases: &[(Value, String)]) {
        let r_val = self.reg_allocator.get_reg_name(value);
        let default_label = format!(".L_{}_{}", self.current_func_name, default_bb);

        for (cv, case_bb) in cases {
            let case_label = format!(".L_{}_{}", self.current_func_name, case_bb);
            if let Value::ConstInt { value: cv_val, .. } = cv {
                if *cv_val == 0 {
                    self.asm_lines.push(format!("    beq {}, r0, {}", r_val, case_label));
                } else {
                    let r_cmp = self.get_temp_reg(&[&r_val]);
                    self.asm_lines.push(format!("    movi {}, {}", r_cmp, cv_val));
                    self.asm_lines.push(format!("    beq {}, {}, {}", r_val, r_cmp, case_label));
                }
            }
        }
        self.asm_lines.push(format!("    j {}", default_label));
    }

    fn emit_call(&mut self, result: &Option<Value>, callee_name: &str, args: &[Value]) {
        for (i, arg) in args.iter().enumerate().take(7) {
            let preg = regalloc::param_reg(i);
            let r_arg = self.reg_allocator.get_reg_name(arg);
            if r_arg != format!("r{}", preg) {
                self.asm_lines.push(format!("    mov r{}, {}", preg, r_arg));
            }
        }
        self.asm_lines.push(format!("    call .L_{}", callee_name));
        if let Some(ref result) = result {
            let r_result = self.reg_allocator.get_reg_name(result);
            if r_result != "r1" {
                self.asm_lines.push(format!("    mov {}, r1", r_result));
            }
        }
    }

    fn emit_call_indirect(&mut self, result: &Option<Value>, fnptr: &Value, args: &[Value]) {
        for (i, arg) in args.iter().enumerate().take(7) {
            let preg = regalloc::param_reg(i);
            let r_arg = self.reg_allocator.get_reg_name(arg);
            if r_arg != format!("r{}", preg) {
                self.asm_lines.push(format!("    mov r{}, {}", preg, r_arg));
            }
        }
        let r_fnptr = self.reg_allocator.get_reg_name(fnptr);
        self.asm_lines.push(format!("    callreg {}", r_fnptr));
        if let Some(ref result) = result {
            let r_result = self.reg_allocator.get_reg_name(result);
            if r_result != "r1" {
                self.asm_lines.push(format!("    mov {}, r1", r_result));
            }
        }
    }

    fn emit_ret(&mut self, value: &Option<Value>) {
        if let Some(ref v) = value {
            let r_val = self.reg_allocator.get_reg_name(v);
            if r_val != "r1" {
                self.asm_lines.push(format!("    mov r1, {}", r_val));
            }
        }
        // RISC: jump to epilogue
        self.asm_lines.push(format!("    j .L_exit_{}", self.current_func_name));
    }

    fn emit_tail_call(&mut self, callee_name: &str, args: &[Value]) {
        for (i, arg) in args.iter().enumerate().take(7) {
            let preg = regalloc::param_reg(i);
            let r_arg = self.reg_allocator.get_reg_name(arg);
            if r_arg != format!("r{}", preg) {
                self.asm_lines.push(format!("    mov r{}, {}", preg, r_arg));
            }
        }
        self.asm_lines.push(format!("    j .L_{}", callee_name));
    }

    // =====================================================================
    //  Float
    // =====================================================================

    fn emit_float_binary(&mut self, inst: &Instruction) {
        let (result, lhs, rhs) = match inst {
            Instruction::Fadd { result, lhs, rhs }
            | Instruction::Fsub { result, lhs, rhs }
            | Instruction::Fmul { result, lhs, rhs }
            | Instruction::Fdiv { result, lhs, rhs }
            | Instruction::Fmin { result, lhs, rhs }
            | Instruction::Fmax { result, lhs, rhs } => (result, lhs, rhs),
            _ => return,
        };
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_lhs = self.reg_allocator.get_reg_name(lhs);
        let r_rhs = self.reg_allocator.get_reg_name(rhs);
        self.asm_lines.push(format!("    {} {}, {}, {}", inst.opcode(), r_dest, r_lhs, r_rhs));
    }

    fn emit_float_unary(&mut self, inst: &Instruction) {
        let (result, operand) = match inst {
            Instruction::Fneg { result, operand }
            | Instruction::Fabs { result, operand }
            | Instruction::Fsqrt { result, operand } => (result, operand),
            _ => return,
        };
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_src = self.reg_allocator.get_reg_name(operand);
        self.asm_lines.push(format!("    {} {}, {}", inst.opcode(), r_dest, r_src));
    }

    fn emit_ffma(&mut self, result: &Value, a: &Value, b: &Value, c: &Value) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_a = self.reg_allocator.get_reg_name(a);
        let r_b = self.reg_allocator.get_reg_name(b);
        let r_c = self.reg_allocator.get_reg_name(c);
        self.asm_lines.push(format!("    fmul {}, {}, {}", r_dest, r_a, r_b));
        self.asm_lines.push(format!("    fadd {}, {}, {}", r_dest, r_dest, r_c));
    }

    fn emit_fcmp(&mut self, inst: &Instruction) {
        let (result, lhs, rhs) = match inst {
            Instruction::FcmpEq { result, lhs, rhs }
            | Instruction::FcmpNe { result, lhs, rhs }
            | Instruction::FcmpLt { result, lhs, rhs }
            | Instruction::FcmpLe { result, lhs, rhs }
            | Instruction::FcmpGt { result, lhs, rhs }
            | Instruction::FcmpGe { result, lhs, rhs }
            | Instruction::FcmpOrd { result, lhs, rhs }
            | Instruction::FcmpUno { result, lhs, rhs } => (result, lhs, rhs),
            _ => return,
        };
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_lhs = self.reg_allocator.get_reg_name(lhs);
        let r_rhs = self.reg_allocator.get_reg_name(rhs);

        let cond = match inst.opcode() {
            "fcmp_eq" => "eq", "fcmp_ne" => "ne",
            "fcmp_lt" => "lt", "fcmp_le" => "le",
            "fcmp_gt" => "gt", "fcmp_ge" => "ge",
            "fcmp_ord" => "ord", "fcmp_uno" => "uno",
            _ => "eq",
        };

        self.asm_lines.push(format!("    fcmp {}, {}", r_lhs, r_rhs));
        self.asm_lines.push(format!("    ; fcmp {} → {}", cond, r_dest));
        self.asm_lines.push(format!("    mov {}, 0", r_dest));

        let skip_label = self.new_label("fcmp");
        match cond {
            "eq" => self.asm_lines.push(format!("    bne {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            "ne" => self.asm_lines.push(format!("    beq {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            "lt" => self.asm_lines.push(format!("    bge {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            "le" => self.asm_lines.push(format!("    bgt {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            "gt" => self.asm_lines.push(format!("    ble {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            "ge" => self.asm_lines.push(format!("    blt {}, {}, .L_{}", r_lhs, r_rhs, skip_label)),
            _ => self.asm_lines.push(format!("    j .L_{}", skip_label)),
        }
        self.asm_lines.push(format!("    movi {}, 1", r_dest));
        self.asm_lines.push(format!(".L_{}:", skip_label));
    }

    // =====================================================================
    //  Conversion
    // =====================================================================

    fn emit_conv(&mut self, inst: &Instruction) {
        match inst {
            Instruction::Sext { result, value, .. }
            | Instruction::Zext { result, value, .. }
            | Instruction::Trunc { result, value, .. } => {
                let r_dest = self.reg_allocator.get_reg_name(result);
                let r_src = self.reg_allocator.get_reg_name(value);
                if let Instruction::Trunc { from_type, .. } = inst {
                    if let IrType::I8 = from_type {
                        self.asm_lines.push(format!("    andi {}, {}, 0xFF", r_dest, r_src));
                        return;
                    } else if let IrType::I16 = from_type {
                        self.asm_lines.push(format!("    andi {}, {}, 0xFFFF", r_dest, r_src));
                        return;
                    }
                }
                if r_dest != r_src {
                    self.asm_lines.push(format!("    mov {}, {}", r_dest, r_src));
                }
            }
            Instruction::Sitofp { result, value, .. }
            | Instruction::Uitofp { result, value, .. } => {
                let r_dest = self.reg_allocator.get_reg_name(result);
                let r_src = self.reg_allocator.get_reg_name(value);
                self.asm_lines.push(format!("    fcvt.s.w {}, {}", r_dest, r_src));
            }
            Instruction::Fptosi { result, value, .. }
            | Instruction::Fptoui { result, value, .. } => {
                let r_dest = self.reg_allocator.get_reg_name(result);
                let r_src = self.reg_allocator.get_reg_name(value);
                self.asm_lines.push(format!("    fcvt.w.s {}, {}", r_dest, r_src));
            }
            Instruction::Fpext { result, value, .. }
            | Instruction::Fptrunc { result, value, .. }
            | Instruction::Bitcast { result, value, .. } => {
                let r_dest = self.reg_allocator.get_reg_name(result);
                let r_src = self.reg_allocator.get_reg_name(value);
                if r_dest != r_src {
                    self.asm_lines.push(format!("    mov {}, {}", r_dest, r_src));
                }
            }
            _ => {}
        }
    }

    // =====================================================================
    //  Auxiliary
    // =====================================================================

    fn emit_select(&mut self, result: &Value, cond: &Value, true_val: &Value, false_val: &Value) {
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_cond = self.reg_allocator.get_reg_name(cond);
        let r_true = self.reg_allocator.get_reg_name(true_val);
        let r_false = self.reg_allocator.get_reg_name(false_val);

        if r_dest != r_false {
            self.asm_lines.push(format!("    mov {}, {}", r_dest, r_false));
        }
        let skip_label = self.new_label("select");
        self.asm_lines.push(format!("    beq {}, r0, .L_{}", r_cond, skip_label));
        if r_dest != r_true {
            self.asm_lines.push(format!("    mov {}, {}", r_dest, r_true));
        }
        self.asm_lines.push(format!(".L_{}:", skip_label));
    }

    // =====================================================================
    //  Vector
    // =====================================================================

    fn emit_vector_binary(&mut self, inst: &Instruction) {
        let (result, lhs, rhs) = match inst {
            Instruction::Vadd { result, lhs, rhs }
            | Instruction::Vsub { result, lhs, rhs }
            | Instruction::Vmul { result, lhs, rhs }
            | Instruction::Vdiv { result, lhs, rhs } => (result, lhs, rhs),
            _ => return,
        };
        let r_dest = self.reg_allocator.get_reg_name(result);
        let r_lhs = self.reg_allocator.get_reg_name(lhs);
        let r_rhs = self.reg_allocator.get_reg_name(rhs);
        self.asm_lines.push(format!("    {} {}, {}, {}", inst.opcode(), r_dest, r_lhs, r_rhs));
    }

    // =====================================================================
    //  Helpers
    // =====================================================================

    fn new_label(&mut self, prefix: &str) -> String {
        let label = format!("{}_{}", prefix, self.label_counter);
        self.label_counter += 1;
        label
    }

    fn get_temp_reg(&self, avoid: &[&str]) -> String {
        let scratch_pool = ["r14", "r15", "r13", "r12", "r8", "r9"];
        for reg in &scratch_pool {
            if !avoid.contains(reg) {
                return reg.to_string();
            }
        }
        "r14".to_string()
    }

    fn format_offset(&self, offset: i64) -> String {
        if offset == 0 {
            " + 0".to_string()
        } else if offset > 0 {
            format!(" + {}", offset)
        } else {
            format!(" - {}", -offset)
        }
    }

    fn resolve_addr_base(&mut self, addr: &AddrExpr) -> String {
        if let Value::GlobalVar { ref name, .. } = addr.base {
            let r_temp = self.get_temp_reg(&[]);
            self.asm_lines.push(format!("    la {}, @{}", r_temp, name));
            return r_temp;
        }
        self.reg_allocator.get_reg_name(&addr.base)
    }

    fn resolve_addr_base_simple(&mut self, base: &Value) -> String {
        if let Value::GlobalVar { ref name, .. } = base {
            let r_temp = self.get_temp_reg(&[]);
            self.asm_lines.push(format!("    la {}, @{}", r_temp, name));
            return r_temp;
        }
        self.reg_allocator.get_reg_name(base)
    }

    fn emit_mem_op(&mut self, _op: &str, reg: &str, addr: &AddrExpr, is_store: bool, sz: &str) {
        let r_base = self.resolve_addr_base(addr);
        let off_str = self.format_offset(addr.offset);

        if let Some(ref index) = addr.index {
            let r_index = self.reg_allocator.get_reg_name(index);
            if is_store {
                self.asm_lines.push(format!(
                    "    str {}, [{} + {}*{}{}]",
                    reg, r_base, r_index, addr.scale, off_str
                ));
            } else {
                self.asm_lines.push(format!(
                    "    ldr {}, [{} + {}*{}{}]",
                    reg, r_base, r_index, addr.scale, off_str
                ));
            }
        } else {
            if is_store {
                match sz {
                    "b" => self.asm_lines.push(format!("    stb {}, [{}{}]", reg, r_base, off_str)),
                    "w" => self.asm_lines.push(format!("    stw {}, [{}{}]", reg, r_base, off_str)),
                    _ => self.asm_lines.push(format!("    st {}, [{}{}]", reg, r_base, off_str)),
                }
            } else {
                match sz {
                    "b" | "h" | "w" => self.asm_lines.push(format!("    ldu {}, [{}{}]", reg, r_base, off_str)),
                    _ => self.asm_lines.push(format!("    ld {}, [{}{}]", reg, r_base, off_str)),
                }
            }
        }
    }

    fn emit_loop_phi_moves(&mut self) {
        if let Some(insert_lines) = self.phi_loop_inserts.get(&self.current_block_name) {
            let lines = insert_lines.clone();
            for line in &lines {
                let parts: Vec<&str> = line.split_whitespace().collect();
                if parts.len() >= 3 && parts[0] == "mov" {
                    let dest_name = parts[1].trim_end_matches(',');
                    let src_name = parts[2];
                    let r_dest = self.reg_allocator.ensure_allocated(dest_name);
                    let r_src = self.reg_allocator.ensure_allocated(src_name);
                    if r_dest != r_src {
                        self.asm_lines.push(format!("    mov {}, {}", r_dest, r_src));
                    }
                }
            }
        }
    }
}

/// Check if an instruction is a terminator.
fn is_terminator(inst: &Instruction) -> bool {
    matches!(
        inst,
        Instruction::Br { .. }
            | Instruction::BrCond { .. }
            | Instruction::Switch { .. }
            | Instruction::Ret { .. }
            | Instruction::TailCall { .. }
    )
}